apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: development
  namespace: flux-system
spec:
  interval: 5m
  url: oci://kind-registry:5000/manifests/demo-config
  insecure: true
  ref:
    tag: latest
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-stack
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: development
  prune: true
  sourceRef:
    kind: OCIRepository
    name: development
  path: ./
  postBuild:
    substitute:
      environment: development
